In [2]:
import pandas as pd
data = pd.read_csv("clean.csv", encoding='utf-8', index_col=0)
data.head()

,date,retweets,likes,text,geo,mention,tag
user,,,,,,,
JuniorPardoXVI,2019-06-24 07:58,0,4,She still had more people at her book signing ...,NaN,@,NaN
brianfires,2019-06-24 07:55,0,1,Tensions Between The US & # Iran Simmered Over...,NaN,@ @,#
JPM86,2019-06-24 07:54,0,0,I got engaged in the sand right there!https://...,NaN,NaN,NaN
kurirona20,2019-06-24 07:49,0,0,K指数5 日経CNBC JPMシゲミ氏(弱気) もともと弱気派だが、投信のセールスもあるせい...,NaN,NaN,NaN
rqYonvqB9iIBJpm,2019-06-24 07:43,0,1,私は、餃子は面倒で造らないんですが。 わたなべ夫婦が造ってると、楽しそうで造ってみたくなります！,NaN,NaN,NaN